# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Installs dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine wheel

    # Builds the package and runs tests
    - name: Build and test
      run: |
        make sdist
        make wheel
        make test

    # If tests pass, pushes the package to TestPyPI
    - name: Push to TestPyPI
      run: |
        make upload-test TEST_PYPI_USER_AGENT=${{ secrets.TEST_PYPI_USER_AGENT }} PYPI_USER_AGENT=${{ secrets.PYPI_USER_AGENT }}

    # Pulls the package from TestPyPI and runs tests
    - name: Pull from TestPyPI and test
      run: |
        pip install --index-url https://test.pypi.org/simple/ user_agent
        # Add commands to run your tests here
        python -m unittest discover

    # If tests pass, pushes the package to PyPI and runs tests
    - name: Push to PyPI
      run: |
        make upload
    # Pulls the package from PyPI and runs tests
    - name: Pull from PyPI and test
      run: |
        pip install user_agent
        python -m unittest discover

    # Updates the version number
    - name: Update version number
      run: |
        make update-version NEW_VERSION=$NEW_VERSION
